config/routes.rb
Rails.application.routes.draw do

  root 'mains#index', as: :index

  get 'mains/contact', as: :contact
  get 'mains/biography', as: :biography
  get 'mains/price', as: :price

  resources :mains
  resources :weddings
  resources :natures

  get 'mains/:id/my_way' => 'mains#my_way', as: :my_way
  

end

app/models/my_way.rb
class MyWay < ActiveRecord::Base
end

app/models/nature.rb
class Nature < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/wedding.rb
class Wedding < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mains_controller.rb
class MainsController < ApplicationController
  def index 
  	@persons = Person.all

  end

  def show
    @person = Person.find(params[:id])
    @persons = Person.all
  end

  def contact
  end

  def biography
  end

  def my_way
  	@my_way = MyWay.find(params[:id])
  end

  def price
  end

end

app/controllers/natures_controller.rb
class NaturesController < ApplicationController
  def show 
  	@nature = Nature.find(params[:id])
    @natures = Nature.all 
  end

  def index
    redirect_to nature_path(1)
  end
end

app/controllers/weddings_controller.rb
class WeddingsController < ApplicationController
  def show 
  	@wedding = Wedding.find(params[:id])
    @weddings = Wedding.all 
  end

  def index
    redirect_to nature_path(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mains_helper.rb
module MainsHelper
end

app/helpers/natures_helper.rb
module NaturesHelper
	
end

app/helpers/weddings_helper.rb
module WeddingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rita Gross</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <meta name="author" content="Rita gross">
    <meta name="description" content="Rita Gross is a creator of cool things that lives on the internet who's based in Minsk, Belarus">
    <meta name="keywords" content="rita ross, vlad, web application, minsk, belarus, commercial photography, editorial photography, freelance photographer">

    <meta name="robots" content="all">
</head>


<%= yield %>


</html>

app/views/mains/biography.html.erb
<body class="biography">

<div id="wrapper">
	<div id="header">
		<p id="logo">Jessica Hilltout</p>
	</div>

	<div id="page-content">
<p>Предполагаемые побудительные мотивы гоголевского творчества, сформулированные уже на первых страницах книги, в дальнейшем никак не развиваются, а только лишь снова и снова подтверждаются прямолинейными суждениями героя-рассказчика и разнообразными биографическими подробностями. Да, Гоголь считал себя “поэтом возможного” (идеального, не-действительного), остро ощущал свою призванность к преобразованию судеб страны и ее народа, пытался посредством художественного (и не только художественного) слова в буквальном смысле переменить, излечить мир — все это описано </p>
<p>Предполагаемые побудительные мотивы гоголевского творчества, сформулированные уже на первых страницах книги, </p>
<p>Three years later, along with a friend, I bought an old jeep, left Belgium and headed east. The journey lasted two years. The jeep took us 80,000km through Central Asia and Africa. The money (or lack of it) forced us to lead a simple life. This was a time to drift and appreciate the countries that nourished our eyes and mind. I took photographs when it felt right, capturing FACES an PLACES, not quite knowing where my work was going.</p>
<p>In retrospect, that trip feels like the start of the way I see things today. I&rsquo;ve often been attracted to &lsquo;un western&rsquo; countries. A certain essential energy shines through everything where the spiritual far outweighs the material. I am interested in the poetic character of things; in the small, seemingly unimportant things. There is hidden beauty in the ordinary, and great beauty in the overlooked.</p>

	</div>									
<br>

 <p class='ritadown'> 
  <a href=<%= mains_path %> id='w1'> главная</a>
  <a href=<%= contact_path %> id='w2'> контакты</a> 
  <a href=<%= biography_path %> id='w4'> биография </a>
  <a href=<%= price_path%> id='w5'> услуги </a>
  <a href=<%= my_way_path(1)%>  id='w6'> мой путь фотографа  </a>
</p> 	

</div>

app/views/mains/contact.html.erb
<body class="contact">

<div id="wrapper">

	<div id="header">
		<p id="logo">Rita Gross</p>
	</div>
	<div id="content">
		<div id="page-content">
		<p>Глубокое, Минск</p>
		<p>+375 29 814 57 01</p>
		<p><a href="mailto:vladislav.spawn@gmail.com">vladislav.spawn@gmail.com</a></p>
		<p><a href="https://vk.com/vlad.hilko">vk.com/vlad.hilko</a></p>		</div>
	</div>

<br>
<br>




 <p class='ritadown'> 
  <a href=<%= mains_path %> id='w1'> главная</a>
  <a href=<%= contact_path %> id='w2'> контакты</a> 
  <a href=<%= biography_path %> id='w4'> биография </a>
  <a href=<%= price_path%> id='w5'> услуги </a>
  <a href=<%= my_way_path(1)%>  id='w6'> мой путь фотографа  </a>
</p>  
		
		
</div>





</body>

app/views/mains/index.html.erb
<body class="home">

<div id="wrapper">

	<div id="header">
		<p id="logo">Jessica Hilltout</p>
	</div>
	<div id="content">
			<ul id="home-pics">
				<li><a href=<%= main_path(1)%> title="Просмотреть индивидуальные фотосеты"><img src=<%= image_url("content/home/people.jpg") %> alt="faces and places" /><span class="caption" >люди</span></a></li>
				<li><a href=<%= wedding_path(1) %> title="Просмотреть свадебную коллекцию"><img src=<%= image_url("content/home/wedding.jpg")%> alt="amen" /><span class="caption">свадьба</span></a></li>
				<li><a href=<%= nature_path(1) %> title="Просмотерть фотографии природы "><img src=<%=image_url("content/home/nature.jpg")%> alt="imperfection" /><span class="caption">природа</span></a></li>
			</ul>
			
	</div>
<br>
<br>
<br>


 <p class='ritadown'> 
  <a href=<%= mains_path %> id='w1'> главная</a>
  <a href=<%= contact_path %> id='w2'> контакты</a> 
  <a href=<%= biography_path %> id='w4'> биография </a>
  <a href=<%= price_path %> id='w5'> услуги </a>
  <a href=<%= my_way_path(1)%>  id='w6'> мой путь фотографа  </a>
</p> 
		
</div>




</body>

app/views/mains/my_way.html.erb
<body class="my-way-of-working 163">

<div id="wrapper">
	<div id="header">
		<p id="logo">Jessica Hilltout</p>
	</div>
	<div id="content">
			<div id="photo">
				<div class="figure wide">
					<%=image_tag(image_url(@my_way.image_url)) %> 
					<p class="caption"></p>
				</div>
				<ul id="pagination">
					<% if @my_way.id == 1 %>
						<li id="nav-previous"><a href=<%=my_way_path(4)%>> previous</a></li>
					    <li id="nav-next"><a href=<%=my_way_path(2) %>></a></li>
					<% end %>
					<% if @my_way.id == 2 %>
							<li id="nav-previous"><a href=<%=my_way_path(1) %>>previous</a></li>
							<li id="nav-next"><a href=<%=my_way_path(3) %>></a></li>
					<% end %>
					<% if @my_way.id == 3 %>
						<li id="nav-previous"><a href=<%=my_way_path(2) %>>previous</a></li>
					    <li id="nav-next"><a href=<%=my_way_path(4) %>></a></li>
					<% end %>
					<% if @my_way.id == 4 %>
							<li id="nav-previous"><a href=<%=my_way_path(3) %>>previous</a></li>
							<li id="nav-next"><a href=<%=my_way_path(1) %>></a></li>
					<% end %>								
				</ul>
			</div>
	</div>
<br>
<br>
<br>
 <p class='ritadown'> 
  <a href=<%= mains_path %> id='w1'> главная</a>
  <a href=<%= contact_path %> id='w2'> контакты</a> 
  <a href=<%= biography_path %> id='w4'> биография </a>
  <a href=<%= price_path%> id='w5'> услуги </a>
  <a href=<%= my_way_path(1)%>  id='w6'> мой путь фотографа  </a>
</p> 	

</div>




</body>

app/views/mains/price.html.erb
<body class="awards-exhibitions-travels">

<div id="wrapper">
	<div id="header">
		<p id="logo">Rita Gross</p>
	</div>
<div id="content">
		<div id="page-content">
<dl>
	<dt>услуги:</dt>
	<dd>Свадебная фотосъёмка</dd>
	<dd>Свадебная видеосъёмка</dd>
	<dd>Love story</dd>
	<dd>Индивидуальные фотосессии</dd>
	<dd>бла-бла-бла</dd>
</dl>
<dl>
	<dt>бла-бла-бла:</dt>
	<dd>2nd place, Kentmere competition, 1998.</dd>
	<dd>3rd place, John Kobal International portrait award.</dd>
	<dd>Sony World Photography Awards finalist. &lsquo;Malagassy Moda&rsquo;, 2009.</dd>
	<dd>Prix de la Photographie Paris (PX3), honerable mention, 2009.</dd>
</dl>
<dl>
	<dt>travels:</dt>
	<dd>Overland to Morocco. Experimenting pinhole camera, 2000.</dd>
	<dd>Overland from Brussels to Mongolia home via Africa.  Faces &amp; Places, 2002.</dd>
	<dd>Sailing from Cape Town to St. Helena. 2007.</dd>
	<dd>Madagascar. Imperfection. 2007.</dd>
	<dd>Africa. AMEN. 2008-2010.</dd>
</dl>
</div>
<br>
<br>

	</div>
 <p class='ritadown'> 
  <a href=<%= mains_path %> id='w1'> главная</a>
  <a href=<%= contact_path %> id='w2'> контакты</a> 
  <a href=<%= biography_path %> id='w4'> биография </a>
  <a href=<%= price_path%> id='w5'> услуги </a>
  <a href=<%= my_way_path(1)%>  id='w6'> мой путь фотографа  </a>
</p> 


</div>


</body>

app/views/mains/show.html.erb
<body class="collections faces 9">

<div id="wrapper">
	<div id="header">
		<p id="logo">Rita Gross</p>
	</div>
	<div id="content">
			<div id="photo">
				<div class="figure">
					<img src=<%= image_url(@person.image_url) %> alt="Mandela Park, Accra." />
					<p class="caption"><%=@person.name %>, <%=@person.city%></p>
				</div>
				<div id="thumbs-carousel">
					<a id="ctrl-prev" href="#">prev</a> <a id="ctrl-next" href="#">next</a>
					<div id="thumbs-wrapper">
						<ul id="thumb-pics">
							
							<% @persons.each do |i| %>
							  <% if i == @person %>
							    <li class="active"><a href="people.html" ><img src=<%= image_url(@person.image_thumb_url) %>  /></a></li>
							    <%next%>
							  <% end %>
								<li><a href=<%=main_path(i)%>> <%= image_tag(image_url(i.image_thumb_url)) %> </a></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
	</div>
</div>

<br>

 <p class='ritadown'> 
  <a href=<%= mains_path %> id='w1'> главная</a>
  <a href=<%= contact_path %> id='w2'> контакты</a> 
  <a href=<%= biography_path %> id='w4'> биография </a>
  <a href=<%= price_path%> id='w5'> услуги </a>
  <a href=<%= my_way_path(1)%>  id='w6'> мой путь фотографа  </a>
</p> 

</div>



</body>

app/views/natures/show.html.erb
<body class="collections faces 9">

<div id="wrapper">
	<div id="header">
		<p id="logo">Rita Gross</p>
	</div>
	<div id="content">
			<div id="photo">
				<div class="figure">
					<img src=<%= image_url(@nature.image_url) %> alt="Mandela Park, Accra." />
					<p class="caption"><%=@nature.name %></p>
				</div>
				<div id="thumbs-carousel">
					<a id="ctrl-prev" href="#">prev</a> <a id="ctrl-next" href="#">next</a>
					<div id="thumbs-wrapper">
						<ul id="thumb-pics">
							
							<% @natures.each do |i| %>
							  <% if i == @nature %>
							    <li class="active"><a href="people.html" ><img src=<%= image_url(@nature.image_thumb_url) %>  /></a></li>
							    <%next%>
							  <% end %>
								<li><a href=<%=nature_path(i)%>> <%= image_tag(image_url(i.image_thumb_url)) %> </a></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
	</div>
</div>

<br>


 <p class='ritadown'> 
  <a href=<%= mains_path %> id='w1'> главная</a>
  <a href=<%= contact_path %> id='w2'> контакты</a> 
  <a href=<%= biography_path %> id='w4'> биография </a>
  <a href=<%= price_path%> id='w5'> услуги </a>
  <a href=<%= my_way_path%>  id='w6'> мой путь фотографа  </a>
</p> 

</div>



</body>

app/views/weddings/show.html.erb
<body class="collections faces 9">

<div id="wrapper">
	<div id="header">
		<p id="logo">Rita Gross</p>
	</div>
	<div id="content">
			<div id="photo">
				<div class="figure">
					<img src=<%= image_url(@wedding.image_url) %> alt="Mandela Park, Accra." />
					<p class="caption"><%=@wedding.name %></p>
				</div>
				<div id="thumbs-carousel">
					<a id="ctrl-prev" href="#">prev</a> <a id="ctrl-next" href="#">next</a>
					<div id="thumbs-wrapper">
						<ul id="thumb-pics">
							
							<% @weddings.each do |i| %>
							  <% if i == @wedding %>
							    <li class="active"><a href="people.html" ><img src=<%= image_url(@wedding.image_thumb_url) %>  /></a></li>
							    <%next%>
							  <% end %>
								<li><a href=<%=wedding_path(i)%>> <%= image_tag(image_url(i.image_thumb_url)) %> </a></li>
							<% end %>
						</ul>
					</div>
				</div>
			</div>
	</div>
</div>

<br>


 <p class='ritadown'> 
  <a href=<%= mains_path %> id='w1'> главная</a>
  <a href=<%= contact_path %> id='w2'> контакты</a> 
  <a href=<%= biography_path %> id='w4'> биография </a>
  <a href=<%= price_path%> id='w5'> услуги </a>
  <a href=<%= my_way_path(1)%>  id='w6'> мой путь фотографа  </a>
</p> 

</div>



</body>